name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_OWNER="nixingshiguang"
GITHUB_REPO="navsphere-data"
GITHUB_BRANCH="main"
NEXTAUTH_URL="https://nxsg-nav.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nxsg-nav.pages.dev"
GITHUB_ID="Ov23lishrT3lidruUdAX"
